### ISSUE TITLE
chat加入非流式模式

### ISSUE THREAD

**Issue by Lt2023** [Lt2023/LLSA#14]
chat的API只能流式返回，应加入非流式，让用户在请求体使用stream参数选择

**Comment by Lt2023** [comment]
@CycleBai

**Comment by CycleBai** [comment]
我认为，以下两个方案会更好一些：
1. 增加一个专门的 /chat_stream 接口，与通用接口分离开。
2. 更改API价格，全面使用 OpenAI API 架构，这样能够做到简单的实现很多功能。
